name: Create and publish the container image.

on:
  push:
    branches:
    tags:

env:
  BASE_REPO: warm-metal/csi-driver-image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.repository == env.BASE_REPO
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        if: github.repository != env.BASE_REPO
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=warmmetal/csi-image,enable=${{ github.repository == env.BASE_REPO }}
            name=ghcr.io/${{ github.repository }},enable=${{ github.repository != env.BASE_REPO }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # set image tag based on GitHub release tag
            type=semver,pattern={{version}}
            # set the image tag based on the branch
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
