name: Create and publish the container image.

on:
  push:
    branches:
    tags:

env:
  # For merging to warmmetal
  #BASE_REPOSITORY: warmmetal/csi-driver-image
  #BASE_IMAGE_NAME: warmmetal/csi-image
  #FORK_IMAGE_NAME: ghcr.io/${{ github.repository }}

  # To do extended tests via my personal repo - mbtamuli/csi-driver-image
  BASE_REPOSITORY: mbtamuli/csi-driver-image
  BASE_IMAGE_NAME: mbtamuli/csi-image
  FORK_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # For debuggging
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.repository == env.BASE_REPOSITORY
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        if: github.repository != env.BASE_REPOSITORY
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.BASE_IMAGE_NAME }},enable=${{ github.repository == env.BASE_REPOSITORY }}
            name=${{ env.FORK_IMAGE_NAME }},enable=${{ github.repository != env.BASE_REPOSITORY }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # set image tag based on GitHub release tag
            type=semver,pattern={{version}}
            # set the image tag based on the branch
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
